### ISSUE TITLE
EEPROMAnything.h: No such file or directory

### ISSUE THREAD

**Issue by gabviv73** [andrewbasterfield/AlarmClock#1]
Trying to compile under 1.6.x Arduino IDE, and got:
  alarm_clock.ino:24:28: fatal error: EEPROMAnything.h: No such file or directory

**Comment by andrewbasterfield** [comment]
Have a look at this page to find the contents of the missing EEPROMAnything.h file

http://playground.arduino.cc/Code/EEPROMWriteAnything

I will have a look at documenting this thanks!

**Comment by andrewbasterfield** [comment]
Added file to repo, closing
